/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { ResumeSectionListRelationFilter } from "../../resumeSection/base/ResumeSectionListRelationFilter";
import { DashboardSettingsListRelationFilter } from "../../dashboardSettings/base/DashboardSettingsListRelationFilter";

@InputType()
class UserWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  firstName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  lastName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  username?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  email?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ResumeSectionListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ResumeSectionListRelationFilter)
  @IsOptional()
  @Field(() => ResumeSectionListRelationFilter, {
    nullable: true,
  })
  resumeSections?: ResumeSectionListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => DashboardSettingsListRelationFilter,
  })
  @ValidateNested()
  @Type(() => DashboardSettingsListRelationFilter)
  @IsOptional()
  @Field(() => DashboardSettingsListRelationFilter, {
    nullable: true,
  })
  dashboardSettingsItems?: DashboardSettingsListRelationFilter;
}

export { UserWhereInput as UserWhereInput };
